name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # build:
  #   runs-on: ubuntu-22.04
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v3
  #     with:
  #       go-version-file: go.mod
  #   - name: Build
  #     run: go build -v ./...
  #   - name: Test
  #     run: go test -v ./...
  
  check:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Run project
      run: docker-compose up -d

    - name: Set up Go for e2e 
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Run E2E tests
      run: go run cmd/e2e/main.go

    - if: failure()
      run: docker-compose ps
    - if: failure()
      run: docker-compose logs
